### PR TITLE
Update 06_plotting_trajectory_trends.py

### PR DESCRIPTION
**Pull request by dongzhuoer**
When you search `compute_trajectory_trends_from_trajectory()` in the repo, the following line of code

```python
def compute_trajectory_trends_from_trajectory(trajectory_ds, ds):
```

lies in `wot/tmap/transport_map_util.py`

### CODE REVIEW

**Comment by dongzhuoer** [comment]
The original code would result the following error:

```
Traceback (most recent call last):
  File "06_plotting_trajectory_trends.py", line 25, in <module>
    results = wot.ot.compute_trajectory_trends_from_trajectory(trajectory_ds, ds)
AttributeError: module 'wot' has no attribute 'ot'
```

**Comment by dongzhuoer** [comment]
The original code would result the following error:

```
Traceback (most recent call last):
  File "06_plotting_trajectory_trends.py", line 25, in <module>
    results = wot.ot.compute_trajectory_trends_from_trajectory(trajectory_ds, ds)
AttributeError: module 'wot' has no attribute 'ot'
```

**Comment by joshua-gould** [comment]
Thanks. I incorporated your fix.

**Comment by geoffschieb** [comment]
Dear Zhouer,

We have just released a tutorial on WOT:
https://broadinstitute.github.io/wot/tutorial/

I'm sending this to anyone who has expressed interest recently.

Best,
Geoff

**Pull request closed without merging**
